#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define SCREEN_WIDTH 480
#define SCREEN_HEIGHT 272
#define TILE_SIZE 16
#define HUD_HEIGHT 21

#define DEFAULT_LEVEL_INDEX 0
#define REGULAR_LEVEL_COUNT 20
#define CAMPAIGN_LEVEL_COUNT 21
#define HIDDEN_LEVEL_INDEX 20
#define SPLASH_PHASE_MS 3750u

#define JUMP_NORMAL    -125
#define JUMP_INVERTED  -180
#define JUMP_POPPED     -95
#define BOUNCE_NORMAL   -83
#define BOUNCE_INVERTED -120
#define BOUNCE_POPPED   -63

#define ACCEL_NORMAL     18
#define ACCEL_BONUS      22
#define MAX_SPEED_NORMAL 60
#define MAX_SPEED_BONUS  100
#define DECEL_GROUNDED   8
#define DECEL_AIRBORNE   3

#define GRAVITY_NORMAL  9
#define MAX_FALL_SPEED 80
#define BONUS_BAR_TICK_DIVISOR 18
#define BONUS_BAR_MAX_UNITS 25

#endif // GAME_CONSTANTS_H
